name: 5-minute-cron

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    job1:
        name: Debug
        runs-on: ubuntu-latest
        
        steps:
        - name: Every time
          run: echo "We ran cron"

